// Code generated by sqlc. DO NOT EDIT.
// Manually written to match sqlc conventions for the documents module.
package db

import (
	"context"
	"database/sql"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (user_id, filename, original_name, mime_type, file_size, storage_path, title, tags)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, filename, original_name, mime_type, file_size, storage_path, title, summary, content_text, tags, created_at, updated_at
`

type CreateDocumentParams struct {
	UserID       int64  `json:"user_id"`
	Filename     string `json:"filename"`
	OriginalName string `json:"original_name"`
	MimeType     string `json:"mime_type"`
	FileSize     int64  `json:"file_size"`
	StoragePath  string `json:"storage_path"`
	Title        string `json:"title"`
	Tags         string `json:"tags"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.UserID,
		arg.Filename,
		arg.OriginalName,
		arg.MimeType,
		arg.FileSize,
		arg.StoragePath,
		arg.Title,
		arg.Tags,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.StoragePath,
		&i.Title,
		&i.Summary,
		&i.ContentText,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, user_id, filename, original_name, mime_type, file_size, storage_path, title, summary, content_text, tags, created_at, updated_at
FROM documents
WHERE id = ? AND user_id = ?
LIMIT 1
`

type GetDocumentParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, arg.ID, arg.UserID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.StoragePath,
		&i.Title,
		&i.Summary,
		&i.ContentText,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, user_id, filename, original_name, mime_type, file_size, storage_path, title, summary, content_text, tags, created_at, updated_at
FROM documents
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context, userID int64) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.FileSize,
			&i.StoragePath,
			&i.Title,
			&i.Summary,
			&i.ContentText,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateDocumentMeta = `-- name: UpdateDocumentMeta :one
UPDATE documents
SET title      = ?,
    summary    = ?,
    tags       = ?,
    updated_at = datetime('now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, filename, original_name, mime_type, file_size, storage_path, title, summary, content_text, tags, created_at, updated_at
`

type UpdateDocumentMetaParams struct {
	Title   string         `json:"title"`
	Summary sql.NullString `json:"summary"`
	Tags    string         `json:"tags"`
	ID      int64          `json:"id"`
	UserID  int64          `json:"user_id"`
}

func (q *Queries) UpdateDocumentMeta(ctx context.Context, arg UpdateDocumentMetaParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentMeta,
		arg.Title,
		arg.Summary,
		arg.Tags,
		arg.ID,
		arg.UserID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.StoragePath,
		&i.Title,
		&i.Summary,
		&i.ContentText,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentContent = `-- name: UpdateDocumentContent :exec
UPDATE documents
SET content_text = ?,
    updated_at   = datetime('now')
WHERE id = ? AND user_id = ?
`

type UpdateDocumentContentParams struct {
	ContentText sql.NullString `json:"content_text"`
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
}

func (q *Queries) UpdateDocumentContent(ctx context.Context, arg UpdateDocumentContentParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentContent, arg.ContentText, arg.ID, arg.UserID)
	return err
}

const updateDocumentSummary = `-- name: UpdateDocumentSummary :exec
UPDATE documents
SET summary    = ?,
    updated_at = datetime('now')
WHERE id = ? AND user_id = ?
`

type UpdateDocumentSummaryParams struct {
	Summary sql.NullString `json:"summary"`
	ID      int64          `json:"id"`
	UserID  int64          `json:"user_id"`
}

func (q *Queries) UpdateDocumentSummary(ctx context.Context, arg UpdateDocumentSummaryParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentSummary, arg.Summary, arg.ID, arg.UserID)
	return err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = ? AND user_id = ?
`

type DeleteDocumentParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, arg.ID, arg.UserID)
	return err
}

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*) FROM documents WHERE user_id = ?
`

func (q *Queries) CountDocuments(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocuments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
