// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, amount, type, category, description, transaction_date)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, amount, type, category, description, transaction_date, created_at
`

type CreateTransactionParams struct {
	UserID          int64   `json:"user_id"`
	Amount          float64 `json:"amount"`
	Type            string  `json:"type"`
	Category        string  `json:"category"`
	Description     string  `json:"description"`
	TransactionDate string  `json:"transaction_date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.Category,
		arg.Description,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Type,
		&i.Category,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, amount, type, category, description, transaction_date, created_at FROM transactions
WHERE user_id = ?
ORDER BY transaction_date DESC, created_at DESC
`

func (q *Queries) ListTransactions(ctx context.Context, userID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ? AND user_id = ?
`

type DeleteTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getFinanceSummary = `-- name: GetFinanceSummary :one
SELECT 
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0.0) AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0.0) AS total_expenses
FROM transactions
WHERE user_id = ?
`

type GetFinanceSummaryRow struct {
	TotalIncome   float64 `json:"total_income"`
	TotalExpenses float64 `json:"total_expenses"`
}

func (q *Queries) GetFinanceSummary(ctx context.Context, userID int64) (GetFinanceSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getFinanceSummary, userID)
	var i GetFinanceSummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpenses)
	return i, err
}
