// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"context"
)

const upsertJournalEntry = `-- name: UpsertJournalEntry :one
INSERT INTO journal_entries (user_id, entry_date, mood_rating, energy_rating, sleep_hours, summary)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id, entry_date) DO UPDATE SET
    mood_rating = EXCLUDED.mood_rating,
    energy_rating = EXCLUDED.energy_rating,
    sleep_hours = EXCLUDED.sleep_hours,
    summary = EXCLUDED.summary,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, entry_date, mood_rating, energy_rating, sleep_hours, summary, created_at, updated_at
`

type UpsertJournalEntryParams struct {
	UserID       int64       `json:"user_id"`
	EntryDate    string      `json:"entry_date"`
	MoodRating   interface{} `json:"mood_rating"`
	EnergyRating interface{} `json:"energy_rating"`
	SleepHours  interface{} `json:"sleep_hours"`
	Summary      string      `json:"summary"`
}

func (q *Queries) UpsertJournalEntry(ctx context.Context, arg UpsertJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, upsertJournalEntry,
		arg.UserID,
		arg.EntryDate,
		arg.MoodRating,
		arg.EnergyRating,
		arg.SleepHours,
		arg.Summary,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryDate,
		&i.MoodRating,
		&i.EnergyRating,
		&i.SleepHours,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalEntryByDate = `-- name: GetJournalEntryByDate :one
SELECT id, user_id, entry_date, mood_rating, energy_rating, sleep_hours, summary, created_at, updated_at FROM journal_entries
WHERE user_id = ? AND entry_date = ? LIMIT 1
`

type GetJournalEntryByDateParams struct {
	UserID    int64  `json:"user_id"`
	EntryDate string `json:"entry_date"`
}

func (q *Queries) GetJournalEntryByDate(ctx context.Context, arg GetJournalEntryByDateParams) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, getJournalEntryByDate, arg.UserID, arg.EntryDate)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryDate,
		&i.MoodRating,
		&i.EnergyRating,
		&i.SleepHours,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, user_id, entry_date, mood_rating, energy_rating, sleep_hours, summary, created_at, updated_at FROM journal_entries
WHERE user_id = ?
ORDER BY entry_date DESC
LIMIT 30
`

func (q *Queries) ListJournalEntries(ctx context.Context, userID int64) ([]JournalEntry, error) {
	rows, err := q.db.QueryContext(ctx, listJournalEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.MoodRating,
			&i.EnergyRating,
			&i.SleepHours,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addJournalItem = `-- name: AddJournalItem :one
INSERT INTO journal_items (entry_id, category, content)
VALUES (?, ?, ?)
RETURNING id, entry_id, category, content, created_at
`

type AddJournalItemParams struct {
	EntryID  int64  `json:"entry_id"`
	Category string `json:"category"`
	Content  string `json:"content"`
}

func (q *Queries) AddJournalItem(ctx context.Context, arg AddJournalItemParams) (JournalItem, error) {
	row := q.db.QueryRowContext(ctx, addJournalItem, arg.EntryID, arg.Category, arg.Content)
	var i JournalItem
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Category,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listJournalItems = `-- name: ListJournalItems :many
SELECT id, entry_id, category, content, created_at FROM journal_items
WHERE entry_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListJournalItems(ctx context.Context, entryID int64) ([]JournalItem, error) {
	rows, err := q.db.QueryContext(ctx, listJournalItems, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalItem
	for rows.Next() {
		var i JournalItem
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Category,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteJournalItem = `-- name: DeleteJournalItem :exec
DELETE FROM journal_items
WHERE id = ?
`

func (q *Queries) DeleteJournalItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJournalItem, id)
	return err
}
