// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"context"
)

const createLearningTrack = `-- name: CreateLearningTrack :one
INSERT INTO learning_tracks (user_id, title, category, description, current_streak, longest_streak)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, title, category, description, current_streak, longest_streak, created_at, updated_at
`

type CreateLearningTrackParams struct {
	UserID        int64  `json:"user_id"`
	Title         string `json:"title"`
	Category      string `json:"category"`
	Description   string `json:"description"`
	CurrentStreak int64  `json:"current_streak"`
	LongestStreak int64  `json:"longest_streak"`
}

func (q *Queries) CreateLearningTrack(ctx context.Context, arg CreateLearningTrackParams) (LearningTrack, error) {
	row := q.db.QueryRowContext(ctx, createLearningTrack,
		arg.UserID,
		arg.Title,
		arg.Category,
		arg.Description,
		arg.CurrentStreak,
		arg.LongestStreak,
	)
	var i LearningTrack
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.Description,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLearningTracks = `-- name: ListLearningTracks :many
SELECT id, user_id, title, category, description, current_streak, longest_streak, created_at, updated_at FROM learning_tracks
WHERE user_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListLearningTracks(ctx context.Context, userID int64) ([]LearningTrack, error) {
	rows, err := q.db.QueryContext(ctx, listLearningTracks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningTrack
	for rows.Next() {
		var i LearningTrack
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Category,
			&i.Description,
			&i.CurrentStreak,
			&i.LongestStreak,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLearningTrack = `-- name: DeleteLearningTrack :exec
DELETE FROM learning_tracks
WHERE id = ? AND user_id = ?
`

type DeleteLearningTrackParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteLearningTrack(ctx context.Context, arg DeleteLearningTrackParams) error {
	_, err := q.db.ExecContext(ctx, deleteLearningTrack, arg.ID, arg.UserID)
	return err
}

const addLearningSession = `-- name: AddLearningSession :one
INSERT INTO learning_sessions (track_id, duration_minutes, summary, session_date)
VALUES (?, ?, ?, ?)
RETURNING id, track_id, duration_minutes, summary, session_date, created_at
`

type AddLearningSessionParams struct {
	TrackID         int64  `json:"track_id"`
	DurationMinutes int64  `json:"duration_minutes"`
	Summary         string `json:"summary"`
	SessionDate     string `json:"session_date"`
}

func (q *Queries) AddLearningSession(ctx context.Context, arg AddLearningSessionParams) (LearningSession, error) {
	row := q.db.QueryRowContext(ctx, addLearningSession,
		arg.TrackID,
		arg.DurationMinutes,
		arg.Summary,
		arg.SessionDate,
	)
	var i LearningSession
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.DurationMinutes,
		&i.Summary,
		&i.SessionDate,
		&i.CreatedAt,
	)
	return i, err
}

const listLearningSessions = `-- name: ListLearningSessions :many
SELECT id, track_id, duration_minutes, summary, session_date, created_at FROM learning_sessions
WHERE track_id = ?
ORDER BY session_date DESC
`

func (q *Queries) ListLearningSessions(ctx context.Context, trackID int64) ([]LearningSession, error) {
	rows, err := q.db.QueryContext(ctx, listLearningSessions, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningSession
	for rows.Next() {
		var i LearningSession
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.DurationMinutes,
			&i.Summary,
			&i.SessionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
