// Code generated by sqlc or matching model definitions. DO NOT EDIT.
package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID           int64          `json:"id" db:"id"`
	Username     string         `json:"username" db:"username"`
	DisplayName  string         `json:"display_name" db:"display_name"`
	Email        sql.NullString `json:"email" db:"email"`
	PasswordHash string         `json:"password_hash" db:"password_hash"`
	Timezone     string         `json:"timezone" db:"timezone"`
	CreatedAt    time.Time      `json:"created_at" db:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at" db:"updated_at"`
}

type Session struct {
	ID        string    `json:"id" db:"id"`
	UserID    int64     `json:"user_id" db:"user_id"`
	ExpiresAt time.Time `json:"expires_at" db:"expires_at"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

type Setting struct {
	UserID    int64     `json:"user_id" db:"user_id"`
	Key       string    `json:"key" db:"key"`
	Value     string    `json:"value" db:"value"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

type Project struct {
	ID                 int64          `json:"id" db:"id"`
	UserID             int64          `json:"user_id" db:"user_id"`
	Name               string         `json:"name" db:"name"`
	Description        string         `json:"description" db:"description"`
	Status             string         `json:"status" db:"status"`
	Color              string         `json:"color" db:"color"`
	ProgressPercentage int64          `json:"progress_percentage" db:"progress_percentage"`
	TargetDate         sql.NullString `json:"target_date" db:"target_date"`
	GithubUrl          string         `json:"github_url" db:"github_url"`
	GithubStars        int64          `json:"github_stars" db:"github_stars"`
	GithubForks        int64          `json:"github_forks" db:"github_forks"`
	GithubOpenIssues   int64          `json:"github_open_issues" db:"github_open_issues"`
	GithubLanguage     string         `json:"github_language" db:"github_language"`
	GithubLastPushedAt sql.NullString `json:"github_last_pushed_at" db:"github_last_pushed_at"`
	TechStack          string         `json:"tech_stack" db:"tech_stack"`
	CreatedAt          time.Time      `json:"created_at" db:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at" db:"updated_at"`
}

type Milestone struct {
	ID          int64          `json:"id" db:"id"`
	ProjectID   int64          `json:"project_id" db:"project_id"`
	Title       string         `json:"title" db:"title"`
	DueDate     sql.NullString `json:"due_date" db:"due_date"`
	IsCompleted bool           `json:"is_completed" db:"is_completed"`
	CompletedAt sql.NullString `json:"completed_at" db:"completed_at"`
	CreatedAt   time.Time      `json:"created_at" db:"created_at"`
}

type Task struct {
	ID               int64          `json:"id" db:"id"`
	UserID           int64          `json:"user_id" db:"user_id"`
	ProjectID        sql.NullInt64  `json:"project_id" db:"project_id"`
	Title            string         `json:"title" db:"title"`
	Description      string         `json:"description" db:"description"`
	Status           string         `json:"status" db:"status"`
	Priority         string         `json:"priority" db:"priority"`
	EnergyLevel      string         `json:"energy_level" db:"energy_level"`
	DueDate          sql.NullString `json:"due_date" db:"due_date"`
	EstimatedMinutes sql.NullInt64  `json:"estimated_minutes" db:"estimated_minutes"`
	ActualMinutes    sql.NullInt64  `json:"actual_minutes" db:"actual_minutes"`
	CompletedAt      sql.NullString `json:"completed_at" db:"completed_at"`
	CreatedAt        time.Time      `json:"created_at" db:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at" db:"updated_at"`
}

type TaskLabel struct {
	TaskID int64  `json:"task_id" db:"task_id"`
	Label  string `json:"label" db:"label"`
}

type TaskDependency struct {
	TaskID      int64 `json:"task_id" db:"task_id"`
	DependsOnID int64 `json:"depends_on_id" db:"depends_on_id"`
}

type Note struct {
	ID        int64         `json:"id" db:"id"`
	UserID    int64         `json:"user_id" db:"user_id"`
	ProjectID sql.NullInt64 `json:"project_id" db:"project_id"`
	Title     string        `json:"title" db:"title"`
	Content   string        `json:"content" db:"content"`
	IsPinned  bool          `json:"is_pinned" db:"is_pinned"`
	CreatedAt time.Time     `json:"created_at" db:"created_at"`
	UpdatedAt time.Time     `json:"updated_at" db:"updated_at"`
}

type NoteTag struct {
	NoteID int64  `json:"note_id" db:"note_id"`
	Tag    string `json:"tag" db:"tag"`
}

type NoteLink struct {
	SourceNoteID int64 `json:"source_note_id" db:"source_note_id"`
	TargetNoteID int64 `json:"target_note_id" db:"target_note_id"`
}

type JournalEntry struct {
	ID           int64           `json:"id" db:"id"`
	UserID       int64           `json:"user_id" db:"user_id"`
	EntryDate    string          `json:"entry_date" db:"entry_date"`
	MoodRating   sql.NullInt64   `json:"mood_rating" db:"mood_rating"`
	EnergyRating sql.NullInt64   `json:"energy_rating" db:"energy_rating"`
	SleepHours  sql.NullFloat64 `json:"sleep_hours" db:"sleep_hours"`
	Summary      string          `json:"summary" db:"summary"`
	CreatedAt    time.Time       `json:"created_at" db:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at" db:"updated_at"`
}

type JournalItem struct {
	ID        int64     `json:"id" db:"id"`
	EntryID   int64     `json:"entry_id" db:"entry_id"`
	Category  string    `json:"category" db:"category"`
	Content   string    `json:"content" db:"content"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

type SearchIndexRow struct {
	EntityType string  `json:"entity_type"`
	EntityID   int64   `json:"entity_id"`
	UserID     int64   `json:"user_id"`
	Title      string  `json:"title"`
	Content    string  `json:"content"`
	Tags       string  `json:"tags"`
	Rank       float64 `json:"rank"`
}

type Transaction struct {
	ID              int64     `json:"id" db:"id"`
	UserID          int64     `json:"user_id" db:"user_id"`
	Amount          float64   `json:"amount" db:"amount"`
	Type            string    `json:"type" db:"type"`
	Category        string    `json:"category" db:"category"`
	Description     string    `json:"description" db:"description"`
	TransactionDate string    `json:"transaction_date" db:"transaction_date"`
	CreatedAt       time.Time `json:"created_at" db:"created_at"`
}

type Budget struct {
	ID           int64     `json:"id" db:"id"`
	UserID       int64     `json:"user_id" db:"user_id"`
	Category     string    `json:"category" db:"category"`
	MonthlyLimit float64   `json:"monthly_limit" db:"monthly_limit"`
	CreatedAt    time.Time `json:"created_at" db:"created_at"`
}

type LearningTrack struct {
	ID            int64     `json:"id" db:"id"`
	UserID        int64     `json:"user_id" db:"user_id"`
	Title         string    `json:"title" db:"title"`
	Category      string    `json:"category" db:"category"`
	Description   string    `json:"description" db:"description"`
	CurrentStreak int64     `json:"current_streak" db:"current_streak"`
	LongestStreak int64     `json:"longest_streak" db:"longest_streak"`
	CreatedAt     time.Time `json:"created_at" db:"created_at"`
	UpdatedAt     time.Time `json:"updated_at" db:"updated_at"`
}

type LearningSession struct {
	ID              int64     `json:"id" db:"id"`
	TrackID         int64     `json:"track_id" db:"track_id"`
	DurationMinutes int64     `json:"duration_minutes" db:"duration_minutes"`
	Summary         string    `json:"summary" db:"summary"`
	SessionDate     string    `json:"session_date" db:"session_date"`
	CreatedAt       time.Time `json:"created_at" db:"created_at"`
}

type Document struct {
	ID           int64          `json:"id" db:"id"`
	UserID       int64          `json:"user_id" db:"user_id"`
	Filename     string         `json:"filename" db:"filename"`
	OriginalName string         `json:"original_name" db:"original_name"`
	MimeType     string         `json:"mime_type" db:"mime_type"`
	FileSize     int64          `json:"file_size" db:"file_size"`
	StoragePath  string         `json:"storage_path" db:"storage_path"`
	Title        string         `json:"title" db:"title"`
	Summary      sql.NullString `json:"summary" db:"summary"`
	ContentText  sql.NullString `json:"content_text" db:"content_text"`
	Tags         string         `json:"tags" db:"tags"`
	CreatedAt    time.Time      `json:"created_at" db:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at" db:"updated_at"`
}

