// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"context"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, project_id, title, content, is_pinned)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, project_id, title, content, is_pinned, created_at, updated_at
`

type CreateNoteParams struct {
	UserID    int64       `json:"user_id"`
	ProjectID interface{} `json:"project_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	IsPinned  bool        `json:"is_pinned"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.IsPinned,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, user_id, project_id, title, content, is_pinned, created_at, updated_at FROM notes
WHERE id = ? AND user_id = ? LIMIT 1
`

type GetNoteByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, user_id, project_id, title, content, is_pinned, created_at, updated_at FROM notes
WHERE user_id = ?
ORDER BY is_pinned DESC, updated_at DESC
`

func (q *Queries) ListNotes(ctx context.Context, userID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET project_id = ?, title = ?, content = ?, is_pinned = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, project_id, title, content, is_pinned, created_at, updated_at
`

type UpdateNoteParams struct {
	ProjectID interface{} `json:"project_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	IsPinned  bool        `json:"is_pinned"`
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.IsPinned,
		arg.ID,
		arg.UserID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = ? AND user_id = ?
`

type DeleteNoteParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const addNoteTag = `-- name: AddNoteTag :exec
INSERT INTO note_tags (note_id, tag)
VALUES (?, ?)
ON CONFLICT (note_id, tag) DO NOTHING
`

type AddNoteTagParams struct {
	NoteID int64  `json:"note_id"`
	Tag    string `json:"tag"`
}

func (q *Queries) AddNoteTag(ctx context.Context, arg AddNoteTagParams) error {
	_, err := q.db.ExecContext(ctx, addNoteTag, arg.NoteID, arg.Tag)
	return err
}

const listNoteTags = `-- name: ListNoteTags :many
SELECT tag FROM note_tags
WHERE note_id = ?
`

func (q *Queries) ListNoteTags(ctx context.Context, noteID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNoteTags, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addNoteLink = `-- name: AddNoteLink :exec
INSERT INTO note_links (source_note_id, target_note_id)
VALUES (?, ?)
ON CONFLICT (source_note_id, target_note_id) DO NOTHING
`

type AddNoteLinkParams struct {
	SourceNoteID int64 `json:"source_note_id"`
	TargetNoteID int64 `json:"target_note_id"`
}

func (q *Queries) AddNoteLink(ctx context.Context, arg AddNoteLinkParams) error {
	_, err := q.db.ExecContext(ctx, addNoteLink, arg.SourceNoteID, arg.TargetNoteID)
	return err
}

const getNoteBacklinks = `-- name: GetNoteBacklinks :many
SELECT n.id, n.user_id, n.project_id, n.title, n.content, n.is_pinned, n.created_at, n.updated_at FROM notes n
JOIN note_links nl ON n.id = nl.source_note_id
WHERE nl.target_note_id = ? AND n.user_id = ?
`

type GetNoteBacklinksParams struct {
	TargetNoteID int64 `json:"target_note_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) GetNoteBacklinks(ctx context.Context, arg GetNoteBacklinksParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNoteBacklinks, arg.TargetNoteID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
